matrix:
  include:
    - os: linux
      sudo: false
      before_script:
        - git clone https://github.com/flutter/flutter.git -b stable
      script:
        - ./flutter/bin/flutter test

    - os: linux
      language: android
      licenses:
        - 'android-sdk-preview-license-.+'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
      android:
        components:
          - tools
          - platform-tools
          - android-27
          - build-tools-27.0.3
          - build-tools-26.0.2 # Required for FlutterFire
          - sys-img-armeabi-v7a-google_apis-27
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-android-support
      before_install:
          - mkdir "$ANDROID_HOME/licenses" || true
          - echo -e "\n8933bad161af4178b1185d1a37fbf41ea5269c55" > "$ANDROID_HOME/licenses/android-sdk-license"
          - echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > "$ANDROID_HOME/licenses/android-sdk-preview-license"
      jdk: oraclejdk8
      sudo: false
      before_script:
        - git clone https://github.com/flutter/flutter.git -b stable
      script:
        - ./flutter/bin/flutter -v build apk

    - os: osx
      language: generic
      osx_image: xcode9.3
      before_script:
        - pip2 install six
        - brew update
        - brew install ruby
        - brew install libimobiledevice
        - brew install ideviceinstaller
        - brew install ios-deploy
        - git clone https://github.com/flutter/flutter.git -b stable
      script:
        - ./flutter/bin/flutter -v build ios --no-codesign

cache:
  directories:
    - $HOME/.pub-cache