name: flutter_libraries_playground
description: Flutter Libraries Playground

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

  kiwi: ^0.1.0
  rxdart: ^0.19.0
  dio: ^1.0.9
  json_annotation: ^2.0.0
  cached_network_image: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^4.0.0

  build_runner: ^1.0.0
  kiwi_generator: ^0.2.0
  json_serializable: ^2.0.0

flutter:

  uses-material-design: true